### PR TITLE
Feature/minting

### PR DESCRIPTION
**Pull request by usman-fazil**
Feature : CLR coin minting and deflation.

### CODE REVIEW

**Review by saadrns — COMMENTED** [review]
Please remove singlenode.sh as we already have colord.sh

**Review by saadrns — COMMENTED** [review]
Please add Unit Test Cases of Minting too

**Comment by usman-fazil** [comment]
> Please remove singlenode.sh as we already have colord.sh

done.

**Review by faisalnaveedRNS — APPROVED** [review]

**Review by RNS135 — APPROVED** [review]
Reviewed but Need to write Test Cases.

**Pull request merged**
